name: CI/CD Pipeline for DigitalOcean Droplets

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/narasimha547/simplephp:latest .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/narasimha547/simplephp:latest

      # Step 5: Deploy to DigitalOcean Droplet
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/narasimha547/simplephp:latest
            docker stop simplephp || true
            docker rm simplephp || true
            docker run -d --name simplephp -p 81:80 ${{ secrets.DOCKER_USERNAME }}/narasimha547/simplephp:latest
